name: Build & deploy mpf-docs to missionpinball.org

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate project showcase pages from .yaml files
        run: python build_tools/generate_showcase_pages.py

      - name: Build and deploy site
        #run: mkdocs gh-deploy --force
        run: |
          git config user.name "mike-ci-bot"
          git config user.email "missionpinball@users.noreply.github.com"
          git fetch
          git checkout gh-pages
          git pull
          git checkout main
          mike deploy 0.57 latest
          mike set-default latest

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # upload entire directory
          path: 'site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
